name: Variaveis de ambiente
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "Valor WOrkflow" 
jobs:
  teste-env:
   runs-on : ubuntu-latest
   env: 
     ENV_JOB: "Valor Job" 
   steps:
     -  name: Execucao
        env:
          ENV_ACTION: "Valor action" 
        run:  |
          echo "$ENV_WORKFLOW" 
          echo "$ENV_JOB" 
          echo "$ENV_ACTION" 
     -  name: Execucao2
        env:
          ENV_ACTION: "Valor action - SEGUNDA" 
        run:  |
          echo "$ENV_WORKFLOW" 
          echo "$ENV_JOB" 
          echo "$ENV_ACTION" 
  
  teste-env-2:
   runs-on : ubuntu-latest
   env: 
     ENV_JOB: "Valor Job Segundo" 
   steps:
     -  name: Execucao
        env:
          ENV_ACTION: "Valor action" 
        run:  |
          echo "$ENV_WORKFLOW" 
          echo "$ENV_JOB" 

